import type { Metadata } from 'next'
import './globals.css'
import './fonts.css'
import './animations.css'
import PageWrapper from './page-wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  )
}
